name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        py-version: [3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python version ${{matrix.py-version}} on image ${{matrix.os}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.py-version}}
        
