name: Installing Python

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os:
         - macos-12
        py-version: [3.9]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python version ${{matrix.py-version}} on image ${{matrix.os}}
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.py-version}}
        
